version: '3'
services:
  php-apache-environment:
    container_name: headless-wordpress
    restart: "no"
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app/dist:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: "no"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
